### ISSUE TITLE
Investigate how to implement the automatic question generation using the Wikidata API.

### ISSUE THREAD

**Issue by AlvaroIC** [Arquisoft/wiq_en2a#16]
Investigate how to implement the automatic question generation using the Wikidata API.

**Comment by pelazas** [comment]
I am thinking on using **SPARQL** query service.

I am going to add an example of a query:
``
SELECT ?item ?itemLabel
WHERE
{
  ?item wdt:P31 wd:Q146. 
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". } 
}
``

The first part is similar to a normal SQL query, where you select an item and an itemLabel, but instead of querying from a table, you query from a triple:
wdt:P31 is the statement instanceof, and wd:Q146 represent the class domestic cat

Therefore this query searches for all the instances of cats available.

This already can give us an idea of how to generate questions, for example by looking for a property in a class

**Comment by AlvaroIC** [comment]
The team decided to use Wikidata Query Service instead of the Wikidata API.
